name = "sb-example-web"
compatibility_date = "2025-03-05"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"
observability.enabled = true

[[services]]
binding = "BACKEND"
service = "sb-example-backend"
